# Specify the names of the datasets
dataset_names:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - '23'
  - '24'
  - '25'
  - '26'
  - '27'
  - '28'
  - '29'
  - '30'
  - '31'
  - '32'
  - '33'
  - '34'
  - '35'
  - '36'
  - '37'
  - '38'
  - '39'
  - '40'
  - '41'
  - '42'
  - '43'
  - '44'
  - '45'
  - '46'
  - '47'
  - '48'
  - '49'
  - '50'
  - '51'

slicing_config:
  # Sliding window size
  window_size: [64, 200, 200]
  # Sliding window stride
  stride: [48, 150, 150]

# Specify paths to volumes
volume_config:
  # Raw data
  raw:
    path:
      '0': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00000_s00_uint8.h5'
      '1': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00001_s00_uint8.h5'
      '2': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00002_s00_uint8.h5'
      '3': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00003_s00_uint8.h5'
      '4': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00004_s00_uint8.h5'
      '5': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00005_s00_uint8.h5'
      '6': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00006_s00_uint8.h5'
      '7': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00007_s00_uint8.h5'
      '8': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00008_s00_uint8.h5'
      '9': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00009_s00_uint8.h5'
      '10': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00010_s00_uint8.h5'
      '11': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00011_s00_uint8.h5'
      '12': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00012_s00_uint8.h5'
      '13': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00013_s00_uint8.h5'
      '14': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00014_s00_uint8.h5'
      '15': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00015_s00_uint8.h5'
      '16': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00016_s00_uint8.h5'
      '17': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00017_s00_uint8.h5'
      '18': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00018_s00_uint8.h5'
      '19': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00019_s00_uint8.h5'
      '20': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00020_s00_uint8.h5'
      '21': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00021_s00_uint8.h5'
      '22': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00022_s00_uint8.h5'
      '23': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00023_s00_uint8.h5'
      '24': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00024_s00_uint8.h5'
      '25': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00025_s00_uint8.h5'
      '26': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00026_s00_uint8.h5'
      '27': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00027_s00_uint8.h5'
      '28': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00028_s00_uint8.h5'
      '29': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00029_s00_uint8.h5'
      '30': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00030_s00_uint8.h5'
      '31': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00031_s00_uint8.h5'
      '32': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00032_s00_uint8.h5'
      '33': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00033_s00_uint8.h5'
      '34': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00034_s00_uint8.h5'
      '35': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00035_s00_uint8.h5'
      '36': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00036_s00_uint8.h5'
      '37': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00037_s00_uint8.h5'
      '38': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00038_s00_uint8.h5'
      '39': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00039_s00_uint8.h5'
      '40': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00040_s00_uint8.h5'
      '41': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00041_s00_uint8.h5'
      '42': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00042_s00_uint8.h5'
      '43': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00043_s00_uint8.h5'
      '44': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00044_s00_uint8.h5'
      '45': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00045_s00_uint8.h5'
      '46': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00046_s00_uint8.h5'
      '47': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00047_s00_uint8.h5'
      '48': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00048_s00_uint8.h5'
      '49': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00049_s00_uint8.h5'
      '50': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00050_s00_uint8.h5'
      '51': '/home/common/Datasets/Marion/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/BDV/uint8_converted/t00051_s00_uint8.h5'
    path_in_h5_dataset: 'channel_s00'
    dtype: float32