# Specify the names of the datasets
dataset_names:
  - '1'

slicing_config:
  # Sliding window size
  window_size:
    '1': [200, 200, 200]
  # Sliding window stride
  stride:
    '1': [150, 150, 150]

# Specify paths to volumes
volume_config:
  # Raw data
  raw:
    path:
      '1': '/g/kreshuk/wolny/Datasets/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous/t00014_s00_uint16_ground_truth_cropped.h5'
    path_in_h5_dataset:
      '1': 'volumes/raw'
    dtype: float32