# The model arguments
model_name: UNet3D
model_kwargs:
  in_channels: 1
  out_channels: 9
  initial_num_fmaps: 12
  fmap_growth: 4
  # how much to downscale in the encoder path (since our data is almost anisotropic downscale equally in each axis)
  scale_factor: [2, 2, 2]
  final_activation: Sigmoid
  conv_type_key: 'vanilla'


training_optimizer_kwargs:
  method: Adam
  lr: 0.0001
  weight_decay: 0.0005

devices:
  - 0
